name: Video Creator
on:
  workflow_dispatch:
    inputs:
      ai_response:
        description: 'AI Data'
        required: true
        type: string

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install gtts requests

      - name: Run Python Script
        env:
          AI_DATA: ${{ github.event.inputs.ai_response }}
        run: python create_video.py

      - name: Save Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Generated-Video
          path: final.mp4
