name: Video Creator
on: repository_dispatch
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          sudo apt-get install ffmpeg
          pip install gtts requests
      - name: Run
        env:
          AI_DATA: ${{ github.event.client_payload.ai_response }}
        run: python create_video.py
